### ISSUE TITLE
error on installing preset

### ISSUE THREAD

**Issue by zynth17** [laravel-presets/vite#1]
i got an error when installing using npx apply laravel:vite --ignore-existing.

"[ error ]  Access to laravel-presets/vite denied. If you think it's an error, make sure you have an SSH key set up and linked to your Git account. If the repository is public and you don't want to configure SSH, use the --no-ssh flag."

**Comment by innocenzi** [comment]
Hello, the solution is in the error message. You should use `npx apply laravel:vite --ignore-existing --no-ssh`. Alternatively (and preferably), [set up an SSH key on your machine](https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account). 👍

**Comment by zynth17** [comment]
hello thankyou for fast replying, it does pass the installation but i got another error because the requirement is php 8
is it possible to make it available with php 7.4?
