### ISSUE TITLE
When doing something destructive (deleting directories) ask the user unless the user has opted in with a flag

### ISSUE THREAD

**Issue by digitaltoad** [laravel-presets/vite#4]
I think this preset assumes it's being used on a new project. That isn't always the case. I think any destructive action that is performed should be prompted unless the user has already opted in from the first run. Even better, allow migration or backup before removing.

**Comment by innocenzi** [comment]
Hey, yes, it totally assumes it's applied in a fresh Laravel project. While there could be prompts before each destructive action, given the fact that most of the preset actually removes stuff, I don't think that'd be very useful. 

The better thing to do would be to better advertise that the preset is for fresh Laravel projects.

That being said, if you want to PR so the preset prompts for confirmations in a non-annoying way, I'd be willing to merge. :+1:
