### ISSUE TITLE
Getting access denied when trying to install laravel-vite

### ISSUE THREAD

**Issue by Cjschmidt** [laravel-presets/vite#5]
Can you help with this? 

![image](https://user-images.githubusercontent.com/12168304/141436432-da90b5ed-3b80-4871-9cd6-669104f5f6bb.png)

**Comment by innocenzi** [comment]
Hi, this is a Git-related issue: `host key verification failed`. You should find a solution by typing this error message in Google. 👍 

Alternatively, I think `npx apply https://github.com/laravel-presets/vite` should work too.
